### ISSUE TITLE
Enable WebUI

### ISSUE THREAD

**Issue by cfrstr** [ShoGinn/dump1090#1]
Is there any way to enable to web ui on port 8080?

**Comment by ShoGinn** [comment]
@arlouk the webui for dump1090 is not a feature of this repo, only because I want it to be as simple/low overhead as possible. This is only the executable and does not contain webui.

I recommend using one of the feeders web ui's to visualize the data.

or even use the modesmixer2 web ui which is pretty awesome :)

**Comment by ShoGinn** [comment]
check it out at [modesmixer2 docker container](https://github.com/shoginn/modesmixer2)

**Comment by cfrstr** [comment]
Definitely will, keep up the great work!
